# Generated by Django 3.0.8 on 2022-07-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
